#44 Replace removed ConfigureUtil to support Gradle 9
Applying the plugin with Gradle 9 failed with `NoClassDefFoundError: org/gradle/util/ConfigureUtil` as soon as a `flavour { }` or `criticalTerms { }` block was configured, because Gradle 9 removed `org.gradle.util.ConfigureUtil`.